name: Docker Image CD

on:
  push:
    paths-ignore:
      - '**.md'

jobs:

  build-crawler:

    runs-on: ubuntu-latest
    name: Build Crawler Image

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build image
      run: |
        docker build . \
          --file ./Crawler/Dockerfile \
          --tag supercharge/crawler:latest
    - name: Push image
      run: |
        docker login -u zekroTJA -p ${{ secrets.DOCKER_PASSWORD }}
        docker supercharge/crawler:latest
        
  build-restapi:

    runs-on: ubuntu-latest
    name: Build RestAPI Image

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build image
      run: |
        docker build . \
          --file ./RestAPI/Dockerfile \
          --tag supercharge/restapi:latest
    - name: Push image
      run: |
        docker login -u zekro -p ${{ secrets.DOCKER_PASSWORD }}
        docker push supercharge/restapi:latest

  build-webapp:

    runs-on: ubuntu-latest
    name: Build WebApp Image

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build image
      run: |
        docker build ./WebApp \
          --file ./WebApp/Dockerfile \
          --tag supercharge/webapp:latest
    - name: Push image
      run: |
        docker login -u zekro -p ${{ secrets.DOCKER_PASSWORD }}
        docker push supercharge/webapp:latest
